export enum Path {
  login = "/login",
  qrcScreen = "/",
  addQrc = "/addqrc",
  qrcDetail = "/qrcdetail",
  country = "/country",
  addCountry = "/addcountry",
  province = "/province",
  addProvince = "/addprovince",
  city = "/city",
  addCity = "/addcity",
  center = "/center",
  users = "/users",
  answer = "/answer",
  answerDetail = "/answerdetail",
  expertProfile = "/expert",
  editProfile = "/editeProfile",
  expertScan = "/expert/scan",
  expertCode = "/expert/code",
  codeDetail = "/codedetail",
  setting = "/setting",
  settingProfile = "/profile/setting",
  dashboard = "/dashboard",
  creatQuestion = "/creatquestion",
  questionsList = "/questionslist",
}
